Repository pnh135/spartify, pull requests merged in 2025-03, with the labels that each got.

#2 🎉 add 페이지 레이아웃 셋팅
  src/app/(pages)/search/page.tsx
  src/app/layout.tsx
  src/components/SideBar.tsx
  tailwind.config.ts
Labels: 제우, 💄스타일링

#5 🎉 add: Home페이지, 레이아웃 세팅
  src/app/layout.tsx
  src/app/page.tsx
  src/components/SideBar.tsx
Labels: 나현, 💄스타일링

#8 Authentication
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/etc-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/app/(pages)/login/page.tsx
  src/app/(pages)/signup/page.tsx
  tailwind.config.ts
Labels: ✨ 기능, 👻영진, 💄스타일링

#21 🐛 bugfix : 페이지 접속 불가 오류 해결 및 zustand 의 authStore.ts 파일 생성 및 기본 로직 구현
  src/app/(pages)/detail/[id]/page.tsx
  src/app/(pages)/example/page.tsx
  src/app/(pages)/login/page.tsx
  src/app/(pages)/profile/page.tsx
  src/app/(pages)/signup/page.tsx
  src/app/api/spotify/album/[id]/route.ts
  src/app/api/spotify/getNewRelease.tsx
  src/app/api/spotify/token/route.ts
  src/app/api/supabase/userAuth.ts
  src/app/zustand/authStore.ts
  src/components/AlbumList.tsx
  src/hooks/queries.tsx
  src/types/album.tsx
  src/types/authentication/auth.ts
  src/types/authentication/supabase.d.ts
Labels: 수민

#23 Feature/signup login
  src/app/(pages)/login/page.tsx
  src/app/(pages)/signup/page.tsx
  src/app/api/supabase/userAuth.ts
  src/store/useUserstore.ts
  src/types/authentication/supabase.d.ts
Labels: ✨ 기능, 👻영진

#24 긴급 에러 수정
  src/app/(pages)/login/page.tsx
  src/app/api/supabase/userAuth.ts
Labels: ⚠️ 버그, 👻영진

#26 Feature/auth layout
  src/app/(pages)/login/page.tsx
  src/app/layout.tsx
  src/components/AuthNav.tsx
Labels: ✨ 기능, 👻영진

#29 Style/alert window
  src/app/(pages)/login/page.tsx
  src/app/(pages)/signup/page.tsx
  src/components/AuthNav.tsx
Labels: 👻영진, 💄스타일링

#37 ♻️ Refactor: Delete src/components/ LikeBtn.tsx
  src/components/ LikeBtn.tsx
Labels: ⚠️ 버그

#40 #40 아티스트 디테일 페이지 앨범 렌더링
  src/app/(pages)/artist/[id]/page.tsx
  src/app/(pages)/detail/[id]/page.tsx
  src/app/(pages)/test/page.tsx
  src/app/api/spotify/artistAlbum/route.ts
  src/app/api/spotify/artistDetail/[id]/route.ts
  src/app/api/spotify/player/route.ts
  src/app/api/spotify/route.ts
  src/app/page.tsx
  src/components/ArtistList.tsx
  src/components/TrackList.tsx
  src/types/album.tsx
  src/types/track.tsx
Labels: ✨ 기능, 📬 API

#43 #43 검색 기능 및 스포티파이 아티스트 타입 지정
  src/app/(pages)/artist/[id]/page.tsx
  src/app/(pages)/detail/[id]/page.tsx
  src/app/(pages)/search/page.tsx
  src/app/api/spotify/album/[id]/route.ts
  src/app/api/spotify/artist/route.ts
  src/app/api/spotify/artistDetail/[id]/route.ts
  src/app/api/spotify/newRelease/route.ts
  src/app/api/spotify/route.ts
  src/app/api/spotify/searchResults/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/AlbumList.tsx
  src/components/ArtistList.tsx
  src/components/SearchBar.tsx
  src/types/album.tsx
  src/types/artist.tsx
Labels: ✨ 기능

#47 Feature/input validation
  package.json
  pnpm-lock.yaml
  src/app/(pages)/login/page.tsx
  src/app/(pages)/signup/page.tsx
  src/components/AuthNav.tsx
  src/components/auth/UserForm.tsx
  src/store/useUserstore.ts
Labels: ✨ 기능, 👻영진, 💄스타일링, ♻️ Refactor

#48 🐛bugfix: 댓글 삭제 기능 오작동 해결
  src/components/CommentList.tsx
Labels: ⚠️ 버그, 정빈, ♻️ Refactor

#52 Feature/third party login
  src/app/(pages)/login/page.tsx
  src/components/AuthNav.tsx
  src/components/auth/ThirdPartyLoginButton.tsx
Labels: ✨ 기능, 👻영진
